#!/usr/bin/python
"""Config file for devicebase.

Import device classes, then define entries in DEVICES as:
   devices(CLASS, HOST, PORT, other_args)
"""
# Function to create record for each device.
from microscope.devices import device
# Import device modules/classes here.
from microscope.testsuite.devices import TestCamera
from microscope.testsuite.devices import TestLaser

DEVICES = [
  device(TestCamera, '127.0.0.1', 8005, otherargs=1,),
  device(TestLaser, '127.0.0.1', 8006),
]
