#!/usr/bin/python
"""Config file for devicebase.

Import device classes, then define entries in DEVICES as:
   devices(CLASS, HOST, PORT, other_args)
"""
# Function to create record for each device.
from microscope.devices import device
# Import device modules/classes here.
# from microscope.testsuite.devices import TestCamera
# from microscope.testsuite.devices import TestLaser
# from microscope.testsuite.devices import TestFilterWheel
from microscope.wavefront_sensors.SID4_SDK import SID4Device

DEVICES = [
    device(SID4Device, '127.0.0.1', 8005)
  # device(TestCamera, '127.0.0.1', 8005, otherargs=1,),
  # device(TestLaser, '127.0.0.1', 8006),
  # device(TestFilterWheel, '127.0.0.1', 8007,
  # filters=[(0, 'GFP', 525), (1, 'RFP'), (2, 'Cy5')]),
]
